version: 2

references:
  circle_node_base: &circle_node_base
    docker:
      - image: circleci/node:10
  restore_npm_local_cache: &restore_npm_local_cache
    restore_cache:
      keys:
        - circle-npm-local-lock-{{ checksum "package-lock.json" }}
  save_npm_local_cache: &save_npm_local_cache
    save_cache:
      key: circle-npm-local-lock-{{ checksum "package-lock.json" }}
      paths:
        - node_modules
  restore_npm_global_cache: &restore_npm_global_cache
    restore_cache:
      keys:
        - circle-npm-global-lock-{{ checksum "package-lock.json" }}
  save_npm_global_cache: &save_npm_global_cache
    save_cache:
      key: circle-npm-global-lock-{{ checksum "package-lock.json" }}
      paths:
        - ~/.npm/_cacache
  npm_install: &npm_install
    run:
      name: Install dependencies if they have not been restored via the cache
      command: |
          if [ ! -d node_modules ]; then
            npm ci || npm install -g npm && npm ci
          fi
  lint: &lint
    run:
      command: "npm run lint"
  unit_test: &unit_test
    run:
      command: |
        if [ -d test/unit ]; then
          npm run test-unit
        fi
  integration_test: &integration_test
    run:
      command: |
        if [ -d test/integration ]; then
          npm run test-integration
        fi
  deploy_service_staging: &deploy_service_staging
    run:
      command: |
        $(npm bin)/serverless deploy --conceal --stage dev --region eu-west-1

jobs:
  install_dependencies:
    <<: *circle_node_base
    steps:
      - checkout
      - *restore_npm_global_cache
      - *restore_npm_local_cache
      - *npm_install
      - *save_npm_global_cache
      - *save_npm_local_cache

  lint:
    <<: *circle_node_base
    steps:
      - checkout
      - *restore_npm_global_cache
      - *restore_npm_local_cache
      - *lint

  unit_test:
    <<: *circle_node_base
    steps:
      - checkout
      - *restore_npm_global_cache
      - *restore_npm_local_cache
      - *unit_test

  integration_test:
    <<: *circle_node_base
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - *restore_npm_global_cache
      - *restore_npm_local_cache
      - *integration_test

  deploy_service_staging:
    <<: *circle_node_base
    steps:
      - checkout
      - *restore_npm_global_cache
      - *restore_npm_local_cache
      - *deploy_service_staging
      - run: mkdir -p workspace
      - persist_to_workspace:
          root: workspace
          paths:
            -.dev-stack.yml

workflows:
  version: 2
  test:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - unit_test:
          requires:
            - lint
      - deploy_service_staging:
          requires:
            - unit_test
      - integration_test:
          requires:
            - deploy_service_staging
