version: 2

references:
  circle_node_base: &circle_node_base
    docker:
      - image: circleci/node:10
  restore_npm_local_cache: &restore_npm_local_cache
    restore_cache:
      keys:
        - circle-npm-local-lock-{{ checksum "package-lock.json" }}
  save_npm_local_cache: &save_npm_local_cache
    save_cache:
      key: circle-npm-local-lock-{{ checksum "package-lock.json" }}
      paths:
        - node_modules
  restore_npm_global_cache: &restore_npm_global_cache
    restore_cache:
      keys:
        - circle-npm-global-lock-{{ checksum "package-lock.json" }}
  save_npm_global_cache: &save_npm_global_cache
    save_cache:
      key: circle-npm-global-lock-{{ checksum "package-lock.json" }}
      paths:
        - ~/.npm/_cacache
  npm_install: &npm_install
    run:
      name: Install dependencies if they have not been restored via the cache
      command: |
          if [ ! -d node_modules ]; then
            npm ci || npm install -g npm && npm ci
          fi
  lint: &lint
    run:
      command: "npm run lint"
      name: "Lint"
  unit_test: &unit_test
    run:
      command: "npm run test-unit"
  integration_test: &integration_test
    run:
      command: "npm run test-integration"

jobs:
  install_dependencies:
    <<: *circle_node_base
    steps:
      - checkout
      - *restore_npm_global_cache
      - *restore_npm_local_cache
      - *npm_install
      - *save_npm_global_cache
      - *save_npm_local_cache

  lint:
    <<: *circle_node_base
    steps:
      - checkout
      - *restore_npm_global_cache
      - *restore_npm_local_cache
      - *npm_install
      - *lint

  unit_test:
    <<: *circle_node_base
    steps:
      - checkout
      - *restore_npm_global_cache
      - *restore_npm_local_cache
      - *npm_install
      - *unit_test

  integration_test:
    <<: *circle_node_base
    steps:
      - checkout
      - *restore_npm_global_cache
      - *restore_npm_local_cache
      - *npm_install
      - *integration_test
  
workflows:
  version: 2
  test:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies           
      - unit_test:
          requires:
            - lint
      - integration_test:
          requires:
            - unit_test
