version: 2.1

orbs:
    change-api: financial-times/change-api@0.25.0

references:
  circle_node_base: &circle_node_base
    docker:
      - image: circleci/node:10

jobs:
  install_dependencies:
    <<: *circle_node_base
    steps:
      - checkout
      - run: npm ci

  lint:
    <<: *circle_node_base
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint

  unit_test:
    <<: *circle_node_base
    steps:
      - checkout
      - run: npm ci
      - run: npm run test-unit

  integration_test:
    <<: *circle_node_base
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: npm ci
      - run: npm run test-integration

  deploy_service_staging:
    <<: *circle_node_base
    steps:
      - checkout
      - run: npm ci
      - run: npx serverless deploy --conceal --stage dev --region eu-west-1
      - persist_to_workspace:
          root: ./
          paths:
            - .dev-stack.yml

  deploy_service_production:
    <<: *circle_node_base
    steps:
      - checkout
      - run: npm ci
      - run:
          command: |
            AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID_PROD} \
            AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_PROD} \
            AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_PROD} \
            REPO_DATA_API_KEY=${REPO_DATA_API_KEY_PROD} \
            REPO_DATA_API_SECRET=${REPO_DATA_API_SECRET_PROD} \
            SENTRY_DSN=${SENTRY_DSN_PROD} \
            SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN_PROD} \
            SENTRY_PROJECT=${SENTRY_PROJECT_PROD} \
            npx serverless deploy --conceal --stage prod --region eu-west-1
      - persist_to_workspace:
          root: ./
          paths:
            - .prod-stack.yml

  update_fastly_production:
    <<: *circle_node_base
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: npm ci
      - run: npm run update-fastly-prod

workflows:
  deploy:
    jobs:
      - lint
      - unit_test
      - deploy_service_staging:
          requires:
            - lint
            - unit_test
      - change-api/release-log:
          requires:
            - deploy_service_staging
          systemCode: 'origami-codedocs'
          environment: 'test'
          slackChannels: 'origami-deploys'
      - integration_test:
          requires:
            - deploy_service_staging
      - deploy_service_production:
          requires:
            - integration_test
          filters:
            branches:
              only:
                - master
      - update_fastly_production:
          requires:
            - deploy_service_production
          filters:
            branches:
              only:
                - master
      - change-api/release-log:
          requires:
            - update_fastly_production
          systemCode: 'origami-codedocs'
          environment: 'prod'
          slackChannels: 'origami-deploys'
          filters:
            branches:
              only:
                - master
